"""
Sales Pipeline --- Unified Daily Digest

Single HTML email combining:
  Section 1: Cold outreach drafts pending review (with A/B variant previews)
  Section 2: Pipeline activity (follow-ups sent, replies, completed sequences)

Sends via Gmail SMTP SSL with App Password.
"""

import json
import logging
import smtplib
from collections import defaultdict
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from sales_pipeline.config import (
    DIGEST_TO_EMAIL,
    GMAIL_APP_PASSWORD,
    GMAIL_SENDER,
    PIPELINE_ID,
    DRAFTS_FILE,
)
from sales_pipeline.state import load_state, get_pipeline_stats, get_needs_decision

log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# HTML builder
# ---------------------------------------------------------------------------

def _build_html(
    cold_drafts: list,
    follow_up_summary: dict,
    opportunities: list,
    stage_names: dict,
    velocity_html: str = "",
) -> str:
    now = datetime.now().strftime("%A, %B %d, %Y %I:%M %p")
    sections = []

    # ---- Header ----
    sections.append(f"""
    <div style="background:#1a1a2e;color:white;padding:20px;border-radius:8px 8px 0 0;">
      <h1 style="margin:0;font-size:22px;">Sales Pipeline Digest</h1>
      <p style="margin:4px 0 0;opacity:0.8;font-size:14px;">{now}</p>
    </div>
    """)

    # ---- Scorecard (top of digest) ----
    sections.append(_build_scorecard(opportunities))

    # ---- Needs Decision ----
    sections.append(_build_needs_decision_section())

    # ---- Section 1: Cold Outreach Drafts ----
    sections.append(_build_cold_section(cold_drafts))

    # ---- Section 2: Follow-Up Activity ----
    sections.append(_build_follow_up_section(follow_up_summary))

    # ---- Section 2.5: Nurture Activity ----
    sections.append(_build_nurture_section(follow_up_summary))

    # ---- Section 2.6: Proposal Views ----
    sections.append(_build_proposal_views_section(follow_up_summary))

    # ---- Section 2.7: Scheduled Messages ----
    sections.append(_build_scheduled_section(follow_up_summary))

    # ---- Section 3: Pipeline Summary ----
    sections.append(_build_pipeline_section(opportunities, stage_names))

    # ---- Section 4: Pipeline Velocity ----
    if velocity_html:
        sections.append(f'<div style="padding:20px;border-bottom:1px solid #eee;">{velocity_html}</div>')

    # ---- Section 5: Learning Insights ----
    sections.append(_build_learning_section())

    body = "\n".join(sections)

    return f"""
    <html><body style="font-family:Arial,sans-serif;max-width:900px;margin:0 auto;
                       background:#f5f5f5;padding:0;">
      <div style="background:white;border-radius:8px;overflow:hidden;
                  box-shadow:0 2px 8px rgba(0,0,0,0.1);margin:20px;">
        {body}
        <div style="padding:12px 20px;background:#f8f8f8;color:#888;font-size:12px;
                    border-top:1px solid #eee;">
          Generated by Americal Patrol Sales Pipeline
        </div>
      </div>
    </body></html>"""


def _build_cold_section(drafts: list) -> str:
    pending = [d for d in drafts if d.get("status") == "pending"]

    if not pending:
        return f"""
        <div style="padding:20px;border-bottom:1px solid #eee;">
          <h2 style="color:#1a1a2e;margin:0 0 8px;">Cold Outreach Drafts</h2>
          <p style="color:#666;">No new drafts pending review.</p>
        </div>"""

    rows = ""
    for d in pending:
        name = d.get("name", "")
        org = d.get("organization", "")
        prop_type = d.get("property_type", "").capitalize()
        channel = d.get("channel", "").upper()
        days = d.get("days_cold", 0)

        # Message preview (use plain text version)
        plain = d.get("message_plain", d.get("message", ""))
        preview = (plain or "")[:250].replace("<", "&lt;").replace(">", "&gt;")
        if len(plain or "") > 250:
            preview += "..."

        # A/B indicator
        has_variant = bool(d.get("variant_b_subject") or d.get("variant_b_message"))
        ab_badge = ('<span style="background:#e3f2fd;color:#1565c0;font-size:11px;'
                    'padding:2px 6px;border-radius:3px;margin-left:6px;">A/B</span>'
                    if has_variant else "")

        # Enrichment indicator
        enriched = d.get("enrichment_matched", False)
        enrich_badge = ('<span style="background:#e8f5e9;color:#2e7d32;font-size:11px;'
                        'padding:2px 6px;border-radius:3px;margin-left:4px;">Enriched</span>'
                        if enriched else "")

        rows += f"""
        <tr>
          <td style="padding:10px;border-bottom:1px solid #f0f0f0;">
            <strong>{name}</strong>{ab_badge}{enrich_badge}<br>
            <span style="color:#666;font-size:13px;">{org}</span>
          </td>
          <td style="padding:10px;border-bottom:1px solid #f0f0f0;">{prop_type}</td>
          <td style="padding:10px;border-bottom:1px solid #f0f0f0;">{channel}</td>
          <td style="padding:10px;border-bottom:1px solid #f0f0f0;">{days}d</td>
          <td style="padding:10px;border-bottom:1px solid #f0f0f0;font-size:13px;color:#333;">
            {preview}
          </td>
        </tr>"""

    return f"""
    <div style="padding:20px;border-bottom:1px solid #eee;">
      <h2 style="color:#1a1a2e;margin:0 0 8px;">Cold Outreach Drafts</h2>
      <p style="background:#fff3cd;padding:12px;border-radius:6px;margin:0 0 12px;">
        <strong>Action required:</strong> {len(pending)} draft(s) pending review.
        Open <code>pipeline_drafts.json</code>, set
        <code>"status": "approved"</code> for contacts to reach, then run:<br>
        <code>python -m sales_pipeline.run_pipeline --send</code>
      </p>
      <table width="100%" style="border-collapse:collapse;">
        <thead>
          <tr style="background:#1a1a2e;color:white;">
            <th style="padding:10px;text-align:left;">Contact</th>
            <th style="padding:10px;text-align:left;">Type</th>
            <th style="padding:10px;text-align:left;">Channel</th>
            <th style="padding:10px;text-align:left;">Cold</th>
            <th style="padding:10px;text-align:left;">Message Preview</th>
          </tr>
        </thead>
        <tbody>{rows}</tbody>
      </table>
    </div>"""


def _build_follow_up_section(summary: dict) -> str:
    sent = summary.get("sent") or []
    replied = summary.get("replied") or []
    completed = summary.get("completed") or []
    cold_drafts = summary.get("cold_drafts_generated") or []
    errors = summary.get("errors") or []

    lines = []

    # Touches sent
    if sent:
        lines.append(f"<strong>Touches sent:</strong> {len(sent)}<ul style='margin:4px 0;'>")
        for item in sent:
            if isinstance(item, dict):
                cid = item.get("contact_id", "?")[:12]
                touch = item.get("touch", "?")
                ch = item.get("channel", "?").upper()
                phase = item.get("phase", "").replace("_", " ").title()
                lines.append(f"<li>{cid} &mdash; Touch #{touch} ({ch}) [{phase}]</li>")
            else:
                lines.append(f"<li>{item}</li>")
        lines.append("</ul>")
    else:
        lines.append("<strong>Touches sent:</strong> 0")

    # Replies
    if replied:
        lines.append(
            f'<strong style="color:#2e7d32;">Replies needing attention:</strong> '
            f'{len(replied)}<ul style="margin:4px 0;">'
        )
        for cid in replied:
            lines.append(f"<li>{cid[:12]}</li>")
        lines.append("</ul>")

    # Cold follow-up drafts generated
    if cold_drafts:
        lines.append(f"<strong>Cold follow-up drafts generated:</strong> {len(cold_drafts)}")

    # Completed
    if completed:
        lines.append(f"<strong>Sequences completed:</strong> {len(completed)}")

    # Errors
    if errors:
        lines.append(
            f'<strong style="color:#c62828;">Errors:</strong> {len(errors)}'
            '<ul style="margin:4px 0;color:#c62828;font-size:13px;">'
        )
        for err in errors[:5]:
            lines.append(f"<li>{err}</li>")
        if len(errors) > 5:
            lines.append(f"<li>...and {len(errors) - 5} more (check automation.log)</li>")
        lines.append("</ul>")

    content = "<br>".join(lines) if lines else "<span style='color:#666;'>No activity today.</span>"

    return f"""
    <div style="padding:20px;border-bottom:1px solid #eee;">
      <h2 style="color:#1a1a2e;margin:0 0 12px;">Follow-Up Activity</h2>
      {content}
    </div>"""


def _build_pipeline_section(opportunities: list, stage_names: dict) -> str:
    if not opportunities:
        return f"""
        <div style="padding:20px;border-bottom:1px solid #eee;">
          <h2 style="color:#1a1a2e;margin:0 0 8px;">Pipeline Summary</h2>
          <p style="color:#666;">No active opportunities in pipeline.</p>
        </div>"""

    by_stage = defaultdict(list)
    for opp in opportunities:
        stage_id = opp.get("pipelineStageId", "unknown")
        label = stage_names.get(stage_id, stage_id)
        by_stage[label].append(opp)

    rows = ""
    for label, opps in sorted(by_stage.items()):
        names = []
        for opp in opps:
            name = opp.get("name", "Unnamed")
            contact = opp.get("contact") or {}
            first = contact.get("firstName", "")
            if first:
                names.append(f"{name} ({first})")
            else:
                names.append(name)
        rows += f"""
        <tr>
          <td style="padding:8px 10px;border-bottom:1px solid #f0f0f0;font-weight:bold;">{label}</td>
          <td style="padding:8px 10px;border-bottom:1px solid #f0f0f0;">{len(opps)}</td>
          <td style="padding:8px 10px;border-bottom:1px solid #f0f0f0;font-size:13px;">
            {", ".join(names)}
          </td>
        </tr>"""

    return f"""
    <div style="padding:20px;border-bottom:1px solid #eee;">
      <h2 style="color:#1a1a2e;margin:0 0 12px;">Pipeline Summary</h2>
      <table width="100%" style="border-collapse:collapse;">
        <thead>
          <tr style="background:#f5f5f5;">
            <th style="padding:8px 10px;text-align:left;">Stage</th>
            <th style="padding:8px 10px;text-align:left;">Count</th>
            <th style="padding:8px 10px;text-align:left;">Opportunities</th>
          </tr>
        </thead>
        <tbody>{rows}</tbody>
      </table>
    </div>"""


def _build_scorecard(opportunities: list) -> str:
    """Pipeline scorecard at the top of the digest."""
    state = load_state()
    stats = get_pipeline_stats(state)

    # Pipeline value from GHL opportunities
    pipeline_value = sum(
        float(opp.get("monetaryValue", 0) or 0)
        for opp in opportunities
        if opp.get("status") == "open"
    )

    cards = []

    def _card(label, value, color="#1a1a2e"):
        return (
            f'<td style="padding:12px;text-align:center;background:#f8f9fa;'
            f'border-radius:8px;width:16%;">'
            f'<div style="font-size:22px;font-weight:bold;color:{color};">{value}</div>'
            f'<div style="font-size:11px;color:#666;margin-top:4px;">{label}</div></td>'
        )

    cards.append(_card("Active", stats["total_active"]))
    cards.append(_card("Cold", stats["cold_outreach"]))
    cards.append(_card("Proposals", stats["post_proposal"]))
    cards.append(_card("Nurture", stats["nurture"]))
    cards.append(_card("Won", stats["won"], "#2e7d32"))

    win_rate = f"{stats['win_rate']:.0f}%" if stats['win_rate'] is not None else "—"
    cards.append(_card("Win Rate", win_rate))

    extra_lines = []
    if pipeline_value > 0:
        extra_lines.append(f"Pipeline value: <strong>${pipeline_value:,.0f}</strong>")
    if stats["days_since_last_win"] is not None:
        extra_lines.append(f"Days since last win: <strong>{stats['days_since_last_win']}</strong>")

    extra_html = ""
    if extra_lines:
        extra_html = (
            '<div style="margin-top:10px;font-size:13px;color:#666;">'
            + " &bull; ".join(extra_lines)
            + "</div>"
        )

    return f"""
    <div style="padding:20px;border-bottom:1px solid #eee;">
      <h2 style="color:#1a1a2e;margin:0 0 12px;font-size:16px;">Pipeline Scorecard</h2>
      <table width="100%" style="border-collapse:separate;border-spacing:8px 0;">
        <tr>{"".join(cards)}</tr>
      </table>
      {extra_html}
    </div>"""


def _build_needs_decision_section() -> str:
    """Contacts that replied but haven't been marked won or lost."""
    state = load_state()
    needs = get_needs_decision(state)

    if not needs:
        return ""

    rows = ""
    for item in needs:
        name = item.get("first_name", "") or item["contact_id"][:12]
        org = item.get("organization", "")
        days = item.get("days_since_reply", 0)
        rows += (
            f'<li><strong>{name}</strong>'
            + (f' ({org})' if org else '')
            + f' — replied {days} days ago</li>'
        )

    return f"""
    <div style="padding:20px;border-bottom:1px solid #eee;">
      <h2 style="color:#c62828;margin:0 0 8px;font-size:16px;">Needs Decision</h2>
      <p style="color:#666;font-size:13px;margin:0 0 8px;">
        These contacts replied but haven't been marked won or lost.
        Run <code>--won CONTACT_ID</code> or <code>--lost CONTACT_ID</code> to resolve.
      </p>
      <ul style="margin:0;padding-left:20px;font-size:14px;">{rows}</ul>
    </div>"""


def _build_nurture_section(summary: dict) -> str:
    """Monthly nurture touches sent."""
    nurture = summary.get("nurture_sent") or []
    if not nurture:
        return ""

    rows = ""
    for item in nurture:
        cid = item.get("contact_id", "?")[:12]
        touch = item.get("nurture_touch", "?")
        ctype = item.get("content_type", "?").replace("_", " ").title()
        rows += f"<li>{cid} — Nurture #{touch} ({ctype})</li>"

    return f"""
    <div style="padding:20px;border-bottom:1px solid #eee;">
      <h2 style="color:#1a1a2e;margin:0 0 8px;font-size:16px;">Monthly Nurture</h2>
      <ul style="margin:0;padding-left:20px;font-size:14px;">{rows}</ul>
    </div>"""


def _build_proposal_views_section(summary: dict) -> str:
    """Proposal view tracking."""
    views = summary.get("proposal_views") or []
    if not views:
        return ""

    rows = ""
    for item in views:
        cid = item.get("contact_id", "?")[:12]
        rows += f'<li style="color:#2e7d32;"><strong>{cid}</strong> — viewed proposal</li>'

    return f"""
    <div style="padding:20px;border-bottom:1px solid #eee;">
      <h2 style="color:#2e7d32;margin:0 0 8px;font-size:16px;">Proposal Views</h2>
      <ul style="margin:0;padding-left:20px;font-size:14px;">{rows}</ul>
    </div>"""


def _build_scheduled_section(follow_up_summary: dict) -> str:
    """Build the scheduled messages section for the digest."""
    scheduled = follow_up_summary.get("scheduled") or []
    cancelled = follow_up_summary.get("cancelled") or []

    if not scheduled and not cancelled:
        return ""

    lines = []

    if scheduled:
        lines.append(f"<strong>Scheduled for delivery ({len(scheduled)}):</strong>")
        lines.append('<ul style="margin:4px 0;">')
        for item in scheduled:
            time_str = item.get("scheduled_for", "immediate")
            if time_str != "immediate":
                try:
                    from sales_pipeline.state import _parse_iso
                    from sales_pipeline.smart_timing import PACIFIC_TZ
                    dt = _parse_iso(time_str)
                    pacific = dt.astimezone(PACIFIC_TZ)
                    time_str = pacific.strftime("%I:%M %p")
                except (ValueError, TypeError):
                    pass
            name = item.get("first_name", "")
            org = item.get("organization", "")
            touch = item.get("touch", "?")
            channel = item.get("channel", "").upper()
            display = f"{name} ({org})" if org else name
            lines.append(
                f'<li><strong>{time_str}</strong> &mdash; {display} '
                f'&mdash; Touch #{touch} {channel}</li>'
            )
        lines.append("</ul>")

    if cancelled:
        lines.append(
            f'<strong style="color:#f57c00;">Cancelled ({len(cancelled)}):</strong>'
        )
        lines.append('<ul style="margin:4px 0;color:#f57c00;">')
        for item in cancelled:
            reason = item.get("reason", "unknown")
            cid = item.get("contact_id", "?")[:12]
            lines.append(f"<li>{cid} &mdash; {reason}</li>")
        lines.append("</ul>")

    content = "\n".join(lines)

    return f"""
    <div style="padding:20px;border-bottom:1px solid #eee;">
      <h2 style="color:#1a1a2e;margin:0 0 12px;">Scheduled Messages</h2>
      {content}
    </div>"""


def _build_learning_section() -> str:
    """Learning system insights."""
    try:
        from sales_pipeline.learning.learning_analyzer import load_insights
        insights = load_insights()
    except Exception:
        return ""

    outcome_count = insights.get("outcome_count", 0)
    reply_rate = insights.get("overall_reply_rate")

    if not outcome_count:
        return ""

    lines = []
    if reply_rate is not None:
        lines.append(f"Overall reply rate: <strong>{reply_rate:.1f}%</strong> ({outcome_count} sends)")

    top = insights.get("top_patterns", {})
    if top:
        for dim, data in top.items():
            label = dim.replace("_", " ").title()
            best = data.get("best", "")
            best_rate = data.get("best_rate", 0)
            if best:
                lines.append(
                    f'{label}: best = <strong>{best}</strong> ({best_rate:.0f}%)'
                )

    if not lines:
        return ""

    content = "<br>".join(lines)

    return f"""
    <div style="padding:20px;border-bottom:1px solid #eee;">
      <h2 style="color:#1a1a2e;margin:0 0 8px;font-size:16px;">Learning Insights</h2>
      <p style="font-size:13px;color:#333;">{content}</p>
    </div>"""


# ---------------------------------------------------------------------------
# Load pending drafts
# ---------------------------------------------------------------------------

def _load_pending_drafts() -> list:
    """Load drafts from pipeline_drafts.json."""
    if not DRAFTS_FILE.exists():
        return []
    try:
        with open(DRAFTS_FILE, "r", encoding="utf-8") as f:
            drafts = json.load(f)
        return drafts if isinstance(drafts, list) else []
    except (json.JSONDecodeError, OSError):
        return []


# ---------------------------------------------------------------------------
# Send digest
# ---------------------------------------------------------------------------

def send_digest(
    ghl_client,
    follow_up_summary: dict,
    stage_names: dict | None = None,
) -> None:
    """
    Build and send the unified daily digest email.

    Args:
        ghl_client:        Authenticated GHLClient instance.
        follow_up_summary: Summary dict from run_follow_ups().
        stage_names:       Optional {stageId: label} map.
    """
    if stage_names is None:
        stage_names = {}

    # Load cold outreach drafts
    cold_drafts = _load_pending_drafts()

    # Fetch pipeline opportunities
    pipeline_id = PIPELINE_ID()
    opportunities = []
    if pipeline_id:
        try:
            opportunities = ghl_client.search_opportunities(pipeline_id)
        except Exception as e:
            log.error("Could not fetch pipeline opportunities: %s", e)

    # Compute pipeline velocity metrics
    velocity_html = ""
    try:
        from sales_pipeline.learning.velocity_tracker import compute_velocity, build_velocity_html
        velocity = compute_velocity()
        velocity_html = build_velocity_html(velocity)
    except Exception as e:
        log.warning("Velocity tracking failed: %s", e)

    html = _build_html(cold_drafts, follow_up_summary, opportunities, stage_names,
                       velocity_html=velocity_html)

    sender = GMAIL_SENDER()
    recipient = DIGEST_TO_EMAIL()
    password = GMAIL_APP_PASSWORD()

    now_str = datetime.now().strftime("%b %d, %Y")
    pending_count = len([d for d in cold_drafts if d.get("status") == "pending"])

    subject_parts = [f"Sales Pipeline Digest \u2014 {now_str}"]
    if pending_count:
        subject_parts.append(f"{pending_count} draft(s) for review")
    if follow_up_summary.get("replied"):
        subject_parts.append(f"{len(follow_up_summary['replied'])} reply(s)")
    subject = " | ".join(subject_parts)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = recipient
    msg.attach(MIMEText(html, "html"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as srv:
            srv.login(sender, password)
            srv.sendmail(sender, recipient, msg.as_string())
        log.info("Digest sent to %s (%d drafts, %d touches, %d replies)",
                 recipient, pending_count,
                 len(follow_up_summary.get("sent", [])),
                 len(follow_up_summary.get("replied", [])))
    except smtplib.SMTPException as e:
        log.error("Failed to send digest: %s", e)
        raise
